import { Prisma } from 'db'

export class CreateAssetDto implements Prisma.AssetCreateInput {
  name: string
}

// If the DTO should not accept full input, you can omit the fields like this:
// export class CreateAssetDto
//   implements Omit<Prisma.AssetCreateInput, 'contractAddress'>
// {
//   contractAddress: string // the contractAddress for an asset is generated by the AssetDeploymentService, it is not defined by user input.
// }
