#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn build --filter=[HEAD^1] && yarn test --filter=[HEAD^1] || echo -e "You have uncommited changes, add them before pushing.\nIf you still want to push, run: \n\n$ git push --no-verify"
