#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn build --filter=HEAD^ && yarn test --filter=HEAD^ || echo -e "You have uncommited changes, add them before pushing.\nIf you still want to push, run: \n\n$ git push --no-verify"
