#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

git diff HEAD --quiet && (yarn build && yarn test) || echo -e "You have uncommited changes, add them before pushing.\nIf you still want to push, run: \n\n$ git push --no-verify"
